name: Commit new data files published at https://data.ontario.ca

# on:
#   schedule:
#     - cron: "*/10 * * * *"

jobs:
  commitDataFile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install Node.js dependencies
      run: npm install

    - name: Create local changes
      run: npm run update

    - name: Commit new data files and the updated latest.json
      run: |
        git config --local user.email "wecount.info@gmail.com"
        git config --local user.name "Auto Update via GitHub Action"
        git add ODC/*
        git commit -m "feat: add a published new data file from https://data.ontario.ca" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
