name: Commit new data files published by Ontario Digial Service

on:
  push:
    branches: [ auto-update-script ]

# on:
#   schedule:
#     - cron: "*/10 * * * *"

jobs:
  dataUpdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install Node.js dependencies
      run: npm ci

    - name: Download the new data file
      id: downloadFile
      run: npm run update

    # Scenarios:
    # 1. When a new file is downloaded, the grep command returns the exit code 1 and causes the step to fail,
    # This results in the command that sets `status` value is not reached, so status == null.
    # 2. When a new file is not found, all commands will execute successfully and status == 0.
    - name: Check if new files are downloaded
      id: checkDownloads
      continue-on-error: true
      run: |
        git status
        git status | grep "nothing to commit"
        echo "::set-output name=status::$?"

    - name: Get the output status
      run: echo "The status was ${{ steps.checkDownloads.outputs.status }}"

    - name: Commit the new data file and the updated latest.json
      if: steps.checkDownloads.outputs.status == null && steps.checkDownloads.outputs.status != 0
      run: |
        git config --local user.email "wecount.info@gmail.com"
        git config --local user.name "Auto Update via GitHub Action"
        git add ODC/*
        git commit -m "feat: add a new data file published at https://data.ontario.ca"

    - name: Push changes
      if: steps.checkDownloads.outputs.status == null && steps.checkDownloads.outputs.status != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
