name: Commit new data files published by Ontario Digital Service and run pipeline to merge with WeCount data

on:
    schedule:
    - cron: "0 23 * * *"

jobs:
    commitNewDataFile:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

        - name: Install Node.js dependencies
          run: npm ci

        - name: Run the pipeline to fetch and merge new data
          id: runPipeline
          run: npm run runPipeline
          env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
