name: Commit new data files published at https://data.ontario.ca

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  downloadDataFile:
    runs-on: ubuntu-latest
    steps:
    - name: Download the new data file
      id: dataUpdate
      uses: cindyli/data-update-action@v1.0.0-alpha

    - name: Get the output status
      run: echo "The time was ${{ steps.dataUpdate.outputs.new-data-file }}"

  # push:
  #   runs-on: ubuntu-latest
  #   needs: downloadDataFile
  #   if: needs.downloadDataFile.outputs.new-data-file != "none"
  #   steps:
  #   - uses: actions/checkout@master
  #     with:
  #       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
  #       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
  #
  #   - name: Commit the new data file and the updated latest.json
  #     run: |
  #       git config --local user.email "wecount.info@gmail.com"
  #       git config --local user.name "Auto Update via GitHub Action"
  #       git add ODC/*
  #       git commit -m "feat: add a published new data file from https://data.ontario.ca" -a
  #
  #   - name: Push changes
  #     uses: ad-m/github-push-action@master
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       branch: ${{ github.ref }}
